/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.41).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Screening;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-03-31T21:52:24.625697542Z[GMT]")
@Validated
public interface ScreeningsApi {

    @Operation(summary = "Retrieve all screenings", description = "", tags={ "Screenings" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A list of all screenings", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Screening.class)))) })
    @RequestMapping(value = "/screenings",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Screening>> screeningsGet();


    @Operation(summary = "Delete a screening by ID", description = "", tags={ "Screenings" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Screening deleted successfully"),
        
        @ApiResponse(responseCode = "404", description = "Screening not found") })
    @RequestMapping(value = "/screenings/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> screeningsIdDelete(@Parameter(in = ParameterIn.PATH, description = "ID of the screening to delete", required=true, schema=@Schema()) @PathVariable("id") Integer id);


    @Operation(summary = "Retrieve a screening by ID", description = "", tags={ "Screenings" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Screening found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Screening.class))),
        
        @ApiResponse(responseCode = "404", description = "Screening not found") })
    @RequestMapping(value = "/screenings/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Screening> screeningsIdGet(@Parameter(in = ParameterIn.PATH, description = "ID of the screening to retrieve", required=true, schema=@Schema()) @PathVariable("id") Integer id);


    @Operation(summary = "Update a screening by ID", description = "", tags={ "Screenings" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Screening updated successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Screening.class))),
        
        @ApiResponse(responseCode = "404", description = "Screening not found") })
    @RequestMapping(value = "/screenings/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Screening> screeningsIdPut(@Parameter(in = ParameterIn.PATH, description = "ID of the screening to update", required=true, schema=@Schema()) @PathVariable("id") Integer id, @Parameter(in = ParameterIn.DEFAULT, description = "Screening object to update", required=true, schema=@Schema()) @Valid @RequestBody Screening body);


    @Operation(summary = "Create a new screening", description = "", tags={ "Screenings" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Screening created successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Screening.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid input") })
    @RequestMapping(value = "/screenings",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Screening> screeningsPost(@Parameter(in = ParameterIn.DEFAULT, description = "Screening object to be created", required=true, schema=@Schema()) @Valid @RequestBody Screening body);

}

