/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.41).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.movies;

import io.swagger.model.Movie;
import io.swagger.model.Reservation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-03-31T21:52:24.625697542Z[GMT]")
@Validated
public interface MoviesApi {

    @Operation(summary = "Get all movies in cinema", description = "", tags={ "Movies" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of all movies that are playing in cinema", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Movie.class)))) })
    @RequestMapping(value = "/movies",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Movie>> moviesGet();


    @Operation(summary = "Delete a movie by ID", description = "", tags={ "Movies" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Movie deleted"),
        
        @ApiResponse(responseCode = "404", description = "Movie not found") })
    @RequestMapping(value = "/movies/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> moviesIdDelete(@Min(1)@Parameter(in = ParameterIn.PATH, description = "ID of the movie to delete", required=true, schema=@Schema(allowableValues={ "1" }, minimum="1"
)) @PathVariable("id") Integer id);


    @Operation(summary = "Get movie by its id", description = "", tags={ "Movies" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Movie with given id", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Movie.class)))),
        
        @ApiResponse(responseCode = "404", description = "Movie not found") })
    @RequestMapping(value = "/movies/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Movie>> moviesIdGet(@Min(1)@Parameter(in = ParameterIn.PATH, description = "ID of the movie to get", required=true, schema=@Schema(allowableValues={ "1" }, minimum="1"
)) @PathVariable("id") Integer id);


    @Operation(summary = "Update a movie by ID", description = "", tags={ "Movies" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "The updated movie", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Movie.class))),
        
        @ApiResponse(responseCode = "404", description = "Movie not found") })
    @RequestMapping(value = "/movies/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Movie> moviesIdPut(@Min(1)@Parameter(in = ParameterIn.PATH, description = "ID of the movie to update", required=true, schema=@Schema(allowableValues={ "1" }, minimum="1"
)) @PathVariable("id") Integer id, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Movie body);


    @Operation(summary = "Reserve a movie", description = "", tags={ "Reservations" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK"),
        
        @ApiResponse(responseCode = "400", description = "Invalid input"),
        
        @ApiResponse(responseCode = "404", description = "Movie not found") })
    @RequestMapping(value = "/movies/{id}/reserve",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> moviesIdReservePost(@Parameter(in = ParameterIn.PATH, description = "ID of the movie to reserve", required=true, schema=@Schema()) @PathVariable("id") Integer id, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Reservation body);


    @Operation(summary = "Create a new movie", description = "", tags={ "Movies" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "The created movie", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Movie.class))) })
    @RequestMapping(value = "/movies",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Movie> moviesPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Movie body);

}

